package wx;

import java.io.IOException;
import java.util.List;

import org.apache.http.client.fluent.Request;

import com.alibaba.fastjson.JSON;

import lombok.Data;

/**
 *
 * Created on 2022-09-23
 */
public class Test {


    private static String getJSON() {
        return "[\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0071\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0053\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0066\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0188\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0191\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 9,\n"
                + "        \"userid\": \"J0116\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0139\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0157\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0196\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0102\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0189\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 8,\n"
                + "        \"userid\": \"J0119\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 10,\n"
                + "        \"userid\": \"J0110\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 7,\n"
                + "        \"userid\": \"J0092\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 11,\n"
                + "        \"userid\": \"Q0001\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 11,\n"
                + "        \"userid\": \"HuangKan\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 11,\n"
                + "        \"userid\": \"Q0120\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 11,\n"
                + "        \"userid\": \"J0147\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"Q0017\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0143\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0151\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0169\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0125\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0160\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0089\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 13,\n"
                + "        \"userid\": \"J0106\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"Q0028\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"Q0260\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"Q0277\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"WangXiaoYun\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"J0177\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"J0146\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 3,\n"
                + "        \"userid\": \"J0149\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"YiLuXiangQianzlh\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"liangyu\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"LiuSanYing\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0178\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0161\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0186\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0154\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0153\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0158\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0190\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"XuAi\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0156\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0168\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0183\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0184\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0181\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0185\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0187\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0159\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 4,\n"
                + "        \"userid\": \"J0097\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 6,\n"
                + "        \"userid\": \"Q0449\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 6,\n"
                + "        \"userid\": \"Q0121\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 6,\n"
                + "        \"userid\": \"J0198\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 6,\n"
                + "        \"userid\": \"J0086\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoZiLiaoJiaoJieCaiWu\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoShuiWu\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoGongShang\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JQ009\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"XiaoQu\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu8\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu10\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoShuiWu5\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"jiqiao3\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoKeJi7\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JQ007\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"ShuiWu7\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu-GuoZhangLaoShi\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"CSC3\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"RenShiZhuanYuan\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"zxl\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"DongXiaoHuan\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"ShuiWu8\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"WX0011\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JianDan-CaiWuZiXun\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu9\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoShuiWu3\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"123\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"JiQiaoCaiWu4-WangLaoShi\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"ChenXiaoJun_1\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"ShuiWu6\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"jiqiao\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 17,\n"
                + "        \"userid\": \"TangChenYuan\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 14,\n"
                + "        \"userid\": \"Q0321\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 18,\n"
                + "        \"userid\": \"Q0208\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 18,\n"
                + "        \"userid\": \"J0027\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 18,\n"
                + "        \"userid\": \"J0029\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 18,\n"
                + "        \"userid\": \"Q0692\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0076\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0059\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0199\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0145\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0081\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0079\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0176\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 15,\n"
                + "        \"userid\": \"J0090\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0048\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0049\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0200\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0195\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"FangJiaHui\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0082\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0094\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0182\"\n"
                + "    },\n"
                + "    {\n"
                + "        \"department\": 16,\n"
                + "        \"userid\": \"J0115\"\n"
                + "    }\n"
                + "]";
    }

    @Data
    public static class DeptUser {
        private String userid;
        private Integer department;
    }

    public static void main(String[] args) {

        List<DeptUser> deptUsers = JSON.parseArray(getJSON(), DeptUser.class);

        String url = "http://testcrm.jiqiao.tech/portrait/wx/simple/employee/%s/customers/autoload";

        deptUsers.parallelStream().forEach(x -> {

            try {
                String str = Request.Get(String.format(url, x.getUserid())).execute().returnContent().asString();
                System.out.println(str);
            } catch (IOException e) {
                System.out.println(e);
            }
        });

        while (true) {

        }


    }
}
